services:
  - type: web
    name: sui-bybit-bot
    env: python
    plan: free
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: PORT
        value: 5000

      # السوق/الإعدادات
      - key: SYMBOL
        value: SUI/USDT:USDT         # لو حصل Unknown market جرّب SUIUSDT:USDT
      - key: INTERVAL
        value: 15m
      - key: LEVERAGE
        value: 10
      - key: POSITION_MODE
        value: oneway
      - key: RISK_ALLOC
        value: "0.60"

      # Range Filter (Pine-exact على الشمعة المغلقة)
      - key: RF_SOURCE
        value: close
      - key: RF_PERIOD
        value: "20"
      - key: RF_MULT
        value: "3.5"

      # مؤشرات (TV-Compat)
      - key: RSI_LEN
        value: "14"
      - key: ADX_LEN
        value: "14"
      - key: ATR_LEN
        value: "14"

      # تنفيذ/إغلاق
      - key: FINAL_CHUNK_QTY
        value: "0.2"
      - key: RESIDUAL_MIN_QTY
        value: "0.05"

      # مفاتيح Bybit (ضيفهم كـ Secrets)
      - key: BYBIT_API_KEY
        sync: false
      - key: BYBIT_API_SECRET
        sync: false

      # Keepalive (اختياري)
      - key: SELF_URL
        value: ""
